### ISSUE TITLE
Support for running migrations for tests

### ISSUE THREAD

**Issue by 1nF0rmed** [nkonev/r2dbc-migrate#20]
I am currently using the spring-starter dependency:
`name.nkonev.r2dbc-migrate:r2dbc-migrate-spring-boot-starter:2.7.6`

And while following the [spring example](https://github.com/nkonev/r2dbc-migrate-example), added migrations under:
`src/main/resources/db/migration`
`src/test/resources/test/migration`

and specified the same paths in the application.yml as:
```
r2dbc:
  migrate:
    resources-paths:
      - classpath:/db/migration/*.sql
      - classpath:/test/migration/*.sql
```

But when running the tests, the test migrations are not run.
Is there a way to trigger these via a gradle task or any configuration needs to be added for the same?
