### ISSUE TITLE
Duplicate column name on H2 with MODE=PostgreSQL

### ISSUE THREAD

**Issue by kressi** [nkonev/r2dbc-migrate#21]
Running migrations on H2 with `MODE=PostgreSQL` causes following exception.

```text
io.r2dbc.spi.R2dbcBadGrammarException: Duplicate column name "?column?"; SQL statement:
insert into "migrations_lock"(id, locked) select * from (select 1, false) x  where not exists(select * from "migrations_lock") [42121-214]
```
I am not sure whether that's an issue of r2dbc-migrate or r2dbc-h2. I don`t understand why that issue occurs.

* Versions
  * `name.nkonev.r2dbc-migrate:r2dbc-migrate-spring-boot-starter:2.7.6`
  * `org.springframework.boot:spring-boot-starter-parent:2.7.1`
* [Complete logs](https://github.com/kressi/r2dbc-migration-h2-issue/runs/7160863632?check_suite_focus=true#step:5:967)
* [application.yml](https://github.com/kressi/r2dbc-migration-h2-issue/blob/main/src/main/resources/application.yml)

**Comment by nkonev** [comment]
Try to force postgres dialect, e. g.
```yaml
spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;MODE=PostgreSQL
    username: sa
    password: ''

r2dbc:
  migrate:
    dialect: POSTGRESQL
    resources-paths:
      - classpath:/db/migration/*.sql
```
